### ISSUE TITLE
[RFC] Subresource metadata

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#2706]
This issue merges multiple subresources issues because the root problem is the same.

While talking with core members at EU-FOSSA Hackathon we came to a solution. Best would be to refactor the `ApiSubresource` annotation so that it supports the same attributes as does the `ApiResource`. For example:

- routing options
- access_control
- normalization context

Thanks to this it'll be easier to declare these and we solve the issue (mentioned in https://github.com/api-platform/core/pull/1617#discussion_r15896391). The subresource metadata will not be in `ApiResource` anymore but directly inside the `ApiSubresource` annotation.

Todo list :

- [ ] Fix swagger and don't show the collection on the side that doesn't own the Subresource (https://github.com/api-platform/core/pull/1612)
- [ ] Fix the serialization context declaration (solves https://github.com/api-platform/core/pull/1617 and https://github.com/api-platform/core/issues/1616 and improves DX for https://github.com/api-platform/core/issues/1649)
- [ ]  Simplified the code for the documentation (ses https://github.com/api-platform/core/issues/1736)
- [ ] Subresource operations may override collection operations which should not happend (see https://github.com/api-platform/api-platform/issues/1022)

consider: https://github.com/api-platform/core/pull/3466  and work on https://github.com/api-platform/core/pull/3689
Maybe that this is a prerequisite for write support on subresources (see #2598 #2428)

ping @torreytsui @vincentchalamon please lmk if I forgot things
@lyrixx I'm closing related PRs we will definitely take back the work you did if we can, thanks for pushing this issues

**Comment by lyrixx** [comment]
Very good move! Can't wait to have it land in APIP :+1:

**Comment by Devristo** [comment]
Would this RFC also help creating custom subresources as described in https://github.com/api-platform/core/issues/1654?

**Comment by teohhanhui** [comment]
> Fix swagger and don't show the collection on the side that doesn't own the Subresource

I disagree. We could show subresource operations in a separate section, maybe? (Not sure if possible with Swagger UI.)

**Comment by dunglas** [comment]
> Not sure if possible with Swagger UI.

AFAIR we tried and it’s not.

**Comment by teohhanhui** [comment]
To answer my own question:

https://github.com/OAI/OpenAPI-Specification/issues/1367
https://github.com/swagger-api/swagger-ui/issues/2129

So, nope.

**Comment by teohhanhui** [comment]
An alternative is to tag them as e.g. `Question (subresource)`?

**Comment by torreytsui** [comment]
I think tagging on the root resource seems the best option we have so far. My thought is that subresource no matter how deep is it (`/foos/1/bars/1/bazs/1/quxs/...`), it starts with the root and the user will have to be aware of it and also consider it.

> Fix the serialization context declaration

Should all levels configure in root (i.e., `foo` below) or spread into each level (i.e., `foo` configure `bar`, and `bar` configure `baz`)?

- `/foos/1/bars/1/bazs`
- `/foos/1/bars/1/bazs/1`
- `/foos/1/bars/1`

Each of above are different operations and it makes sense to have their own independent configurations. How do we explicitly declare them?

How to enable / disable certain operations? At the moment, there are only item GET and collection GET, but when we implement write operations, it will get complicated and escalate as the depth grows.

**Comment by GregoireHebert** [comment]
`Subresource operations may override collection operations which should not happen (see api-platform/api-platform#1022)` 
This does not seems to be the case anymore.

**Comment by GregoireHebert** [comment]
`Fix swagger and don't show the collection on the side that doesn't own the Subresource (#1612)`
Seems to be fixed too.

**Comment by GregoireHebert** [comment]
#1616 is fixed in #3690

**Comment by GregoireHebert** [comment]
I think this could be closed in favour of #3689

**Comment by brunonic** [comment]
`swagger_context` is still not supported under subresource operation ? #1873

**Comment by vincentchalamon** [comment]
Subresource has been deprecated in 2.7 and removed in 3.0

**Comment by vincentchalamon** [comment]
@gigo6000 the `ApiSubresource` has been deprecated in 2.7 and removed in 3.0. The notion of _Subresource_ is still active as everything is an `ApiResource` now
